import { Suspense } from "react";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./Header";
import Footer from "./Footer";
import Loading from "./Loading";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "NEXT.js13 Blog",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="ja">
			<body className="container mx-auto bg-slate-700 text-slate-50">
				<div className="flex flex-col min-h-screen">
					<Header />
					<main className="flex-grow">
						<Suspense fallback={<Loading />}>
							{children}
						</Suspense>
					</main>
					<Footer />
				</div>
			</body>
		</html>
	);
}
